### ISSUE TITLE
Html text formatting

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-online#244]
Add basic html handling (bold, newline etc.) to _longText_ and _item_ fields (maybe other as well?), while keeping other fields preformatted (e.g., _warning_ always bolded).

**Comment by pikrol** [comment]
There is a problem with this HTML longText that it does not have a nice bottom margin (unless someone creates a properly styled div as longText) and it looks a bit ugly. With p() tag as before we had everything styled properly.
![image](https://user-images.githubusercontent.com/44268776/179211002-9572a476-884d-4384-8d65-83acefd1f4a7.png)

What do we do about this? Maybe create another text_type: e.g. longTextHTML? and leave the rest as before.

@karolkiljan @gkrajewski

**Comment by gkrajewski** [comment]
You mean there's not enough space after the paragraph? How about adding some automatically, e.g., an empty line? Would be simpler than adding another text type. @karolkiljan, what do you think?

**Comment by karolkiljan** [comment]
https://github.com/pikrol/CDI-online/pull/264
it looks like we can easily apply html method inside paragraph method
