### ISSUE TITLE
General communication level question not working

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-online#252]
Mam problem z ustawieniem pytania o ogólny poziom rozwoju ([pytanie 11 w załączonym pdfie z angielskimi tłumaczeniami](https://github.com/pikrol/CDI-online/files/8778396/se-cdi-iii_en.pdf)). Chciałem użyć typu `radio`, ale:

- nie wiem, czy da się wtedy odpowiedzi ustawić pionowo, a nie poziomo (może jakoś w css trzeba grzebać)?
- odpowiedzi są długie i niektóre zawierają przecinki, więc nie umiem ich wstawić do `choiceNames` tak, żeby te przecinki nie rozbijały ich na więcej
- nie umiem wprowadzić warunkowości: zaznaczenie pierwszej lub drugiej powinno kończyć (czyli zaznaczenie pozostałych powinno odblokowywać dalsze części)

Dwa pierwsze punkty można pewnie obejść, używając `radioAlt`, ale wtedy już zupełnie nie mam pojęcia, jak ustawić warunkowość...

**Comment by pikrol** [comment]
- da się zmieniać poziomo/pionowo ale to trzeba w kodzie
- a no nie pomyślałem o choiceNames zawierających przecinki. Możemy zmienić znak rozbijający np. na % tylko to musimy we wszystkich formularzach
- musiałbyś wypisać w answers_to_enable wszystkie odpowiedzi, które odblokowują czyli "3,4,5,6"

Ale generalnie prościej będzie chyba użyć właśnie radioAlt, wtedy odblokowywanie ustawiasz tak samo "3,4,5,6" (at least I hope so)

**Comment by gkrajewski** [comment]
Właśnie "3,4,5,6" nie działa: kolejne sekcje pozostają zamknięte.

**Comment by pikrol** [comment]
Faktycznie, sprawdzę jutro dokładnie czemu tak się dzieje

**Comment by pikrol** [comment]
@gkrajewski naprawione. Powodem była obecność pola na komentarz. Teraz warunkowanie typów powinno działać bez względu na to czy jest pole na komentarz czy nie :)

**Comment by gkrajewski** [comment]
Dzięki!!
